# Generated by Django 5.1.3 on 2026-06-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PdfFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "file",
                    models.FileField(upload_to="pdfs/%Y%m%d/", verbose_name="文件"),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="校验和"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="application/pdf",
                        max_length=100,
                        verbose_name="MIME类型",
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(blank=True, null=True, verbose_name="页数"),
                ),
                (
                    "extraction_state",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="提取状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF文件",
                "verbose_name_plural": "PDF文件",
                "db_table": "pdf_file",
            },
        ),
    ]
