# Generated by Django 5.1.3 on 2026-07-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0007_shrink_category_l1'),
        ('documents', '0005_alter_coa_options'),
        ('transactions', '0005_invoicesequence_invoice_payment_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('location', models.CharField(choices=[('MAIN', 'Main Warehouse'), ('EU', 'EU Warehouse'), ('US', 'US Warehouse')], default='MAIN', max_length=20, verbose_name='库位')),
                ('available', models.IntegerField(default=0, verbose_name='可分配量')),
                ('allocated', models.IntegerField(default=0, verbose_name='已占用量')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='documents.batch', verbose_name='批次')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='commerce.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'inventory',
                'ordering': ['sku_id', 'location'],
                'unique_together': {('sku', 'batch', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='占用数量')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('shipped', 'Shipped'), ('released', 'Released')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='transactions.orderitem', verbose_name='订单明细')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.inventory', verbose_name='库存')),
            ],
            options={
                'verbose_name': '库存占用',
                'verbose_name_plural': '库存占用',
                'db_table': 'allocation',
            },
        ),
    ]
