# Generated by Django 5.1.3 on 2026-07-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('to_emails', models.CharField(max_length=2000, verbose_name='收件人')),
                ('cc_emails', models.CharField(blank=True, default='', max_length=2000, verbose_name='抄送')),
                ('subject', models.CharField(max_length=500, verbose_name='主题')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='正文(纯文本)')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='正文(HTML)')),
                ('attachment_paths', models.JSONField(default=list, verbose_name='附件路径列表')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最后错误')),
                ('template_key', models.CharField(blank=True, default='', max_length=100, verbose_name='模板键')),
                ('context_json', models.JSONField(default=dict, verbose_name='渲染上下文')),
            ],
            options={
                'verbose_name': '邮件发件箱',
                'verbose_name_plural': '邮件发件箱',
                'db_table': 'email_outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='模板键')),
                ('subject', models.CharField(max_length=500, verbose_name='主题')),
                ('body_html', models.TextField(blank=True, default='', verbose_name='HTML 正文')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='纯文本正文')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='语言')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'db_table': 'email_template',
            },
        ),
    ]
