# Generated by Django 5.1.3 on 2026-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="session_key",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="会话标识"
            ),
        ),
    ]
