# Generated by Django 5.1.3 on 2026-06-12 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_initial"),
        ("transactions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="basket",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddConstraint(
            model_name="basket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "sku"),
                name="basket_user_sku_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="basket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__gt", ""), ("user__isnull", True)),
                fields=("session_key", "sku"),
                name="basket_session_sku_unique",
            ),
        ),
    ]
