# Generated by Django 5.1.3 on 2026-06-13 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_alternate_email_user_avatar_url_and_more"),
        ("transactions", "0003_basket_support_anonymous"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.TextField(blank=True, default="", verbose_name="账单地址"),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="账单名称"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="internal_notes",
            field=models.TextField(blank=True, default="", verbose_name="内部备注"),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="客户备注"),
        ),
        migrations.AddField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="accounts.organization",
                verbose_name="组织",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="付款到期日"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("purchase_order", "Purchase Order"),
                    ("credit_card", "Credit Card"),
                    ("wire_transfer", "Wire Transfer"),
                    ("quote", "Quote"),
                ],
                default="purchase_order",
                max_length=20,
                verbose_name="付款方式",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_terms",
            field=models.CharField(default="NET30", max_length=20, verbose_name="账期"),
        ),
        migrations.AddField(
            model_name="order",
            name="po_contact",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="PO 联系人"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="po_number",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="PO 号"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True, default="", verbose_name="收货地址"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="收件邮箱"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="收件人"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="收件电话"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="小计"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("confirmed", "Confirmed"),
                    ("invoiced", "Invoiced"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("quote_pending", "Quote Pending"),
                    ("quoted", "Quoted"),
                    ("quote_accepted", "Quote Accepted"),
                    ("quote_rejected", "Quote Rejected"),
                ],
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "invoice_no",
                    models.CharField(max_length=50, unique=True, verbose_name="发票号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开具时间"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="到期日")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="付款时间"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="小计"
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="税费"
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="总计"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=10, verbose_name="币种"),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="付款参考"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="transactions.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "发票",
                "verbose_name_plural": "发票",
                "db_table": "invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online", "Online Payment"),
                            ("wire", "Wire Transfer"),
                            ("check", "Check"),
                        ],
                        max_length=20,
                        verbose_name="付款方式",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="金额"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=10, verbose_name="币种"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="交易参考号",
                    ),
                ),
                (
                    "proof_file",
                    models.FileField(
                        blank=True,
                        default="",
                        upload_to="payment_proofs/%Y/%m/",
                        verbose_name="付款凭证",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="transactions.invoice",
                        verbose_name="发票",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
            ],
            options={
                "verbose_name": "付款记录",
                "verbose_name_plural": "付款记录",
                "db_table": "payment_record",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparing"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="preparing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="物流公司"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="运单号"
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, default="", verbose_name="物流链接"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发货时间"
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateField(blank=True, null=True, verbose_name="预计送达"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送达时间"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping",
                        to="transactions.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "发货记录",
                "verbose_name_plural": "发货记录",
                "db_table": "shipping_record",
            },
        ),
    ]
