# Generated by Django 5.1.3 on 2026-07-10 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _clean_empty_po_numbers(apps):
    """将空 po_number 置为唯一占位符 LEGACY-<id>，避免 unique 约束冲突。"""
    Order = apps.get_model('transactions', 'Order')
    for order in Order.objects.filter(po_number__in=['', None]):
        order.po_number = f'LEGACY-{order.id}'
        order.save(update_fields=['po_number'])



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
        ('transactions', '0004_order_billing_address_order_billing_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '发票序号',
                'verbose_name_plural': '发票序号',
                'db_table': 'invoice_sequence',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(choices=[('NET30', 'Net 30'), ('NET45', 'Net 45'), ('NET60', 'Net 60')], default='NET30', max_length=20, verbose_name='账期'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['procurement', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='负责销售'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='accounts.address', verbose_name='账单地址溯源'),
        ),
        migrations.AddField(
            model_name='order',
            name='etd',
            field=models.DateField(blank=True, null=True, verbose_name='预计发货'),
        ),
        migrations.AddField(
            model_name='order',
            name='grant_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='基金/赞助号'),
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='transactions.quote', verbose_name='关联询价单'),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='期望到货日'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='accounts.address', verbose_name='收货地址溯源'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('ambient', 'Ambient'), ('cold_pack', 'Cold Pack'), ('dry_ice', 'Dry Ice'), ('blue_ice', 'Blue Ice')], default='', max_length=20, verbose_name='运输方式'),
        ),
        migrations.AddField(
            model_name='shippingrecord',
            name='received_by',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='签收人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_terms',
            field=models.CharField(choices=[('NET30', 'Net 30'), ('NET45', 'Net 45'), ('NET60', 'Net 60')], default='NET30', max_length=20, verbose_name='账期'),
        ),
        # ── T7: 清洗历史空 po_number，避免 unique 约束失败（须在 unique 前）──
        migrations.RunPython(
            code=lambda apps, schema_editor: _clean_empty_po_numbers(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='PO 号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('po_received', 'PO Received'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('draft', 'Draft'), ('processing', 'Processing'), ('quote_pending', 'Quote Pending'), ('quoted', 'Quoted'), ('quote_accepted', 'Quote Accepted'), ('quote_rejected', 'Quote Rejected')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='shippingrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='transactions.order', verbose_name='订单'),
        ),
        migrations.CreateModel(
            name='PoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(upload_to='po_attachments/%Y%m/', verbose_name='文件')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='MIME 类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transactions.order', verbose_name='订单')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': 'PO 附件',
                'verbose_name_plural': 'PO 附件',
                'db_table': 'po_attachment',
            },
        ),
        migrations.CreateModel(
            name='ShippingRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='transactions.orderitem', verbose_name='订单明细')),
                ('shipping_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.shippingrecord', verbose_name='发货记录')),
            ],
            options={
                'verbose_name': '发货明细',
                'verbose_name_plural': '发货明细',
                'db_table': 'shipping_record_item',
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action_type', models.CharField(choices=[('status_change', 'Status Change'), ('rep_assigned', 'Rep Assigned'), ('rejected', 'Rejected'), ('noted', 'Noted'), ('shipment', 'Shipment'), ('invoice', 'Invoice')], default='status_change', max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='transactions.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '状态日志',
                'verbose_name_plural': '状态日志',
                'db_table': 'status_log',
                'ordering': ['created_at'],
            },
        ),
    ]
