# Generated by Django 5.1.3 on 2026-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_invoicesequence_invoice_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='PO 号'),
        ),
    ]
