# Generated by Django 5.1.3 on 2026-08-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_order_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('rep_assigned', 'Rep Assigned'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('noted', 'Noted'), ('shipment', 'Shipment'), ('invoice', 'Invoice')], default='status_change', max_length=20),
        ),
    ]
