# Generated by Django 5.1.3 on 2026-06-11 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("display_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                (
                    "status",
                    models.CharField(
                        default="active", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_protocols",
                        to="knowledge.method",
                        verbose_name="方法",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_protocols",
                        to="knowledge.protocol",
                        verbose_name="协议",
                    ),
                ),
            ],
            options={
                "verbose_name": "方法-协议关联",
                "verbose_name_plural": "方法-协议关联",
                "db_table": "method_protocol",
                "indexes": [
                    models.Index(
                        fields=["method", "display_order"],
                        name="method_protocol_order_idx",
                    )
                ],
                "unique_together": {("method", "protocol")},
            },
        ),
        migrations.CreateModel(
            name="ProductCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("compatible", "兼容"),
                            ("incompatible", "不兼容"),
                            ("conditional", "条件兼容"),
                            ("warning", "警告"),
                        ],
                        max_length=20,
                        verbose_name="判定结果",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "compatibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_facts",
                        to="knowledge.compatibility",
                        verbose_name="兼容性规则",
                    ),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_as_source",
                        to="commerce.product",
                        verbose_name="源产品",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_as_target",
                        to="commerce.product",
                        verbose_name="目标产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品兼容性事实",
                "verbose_name_plural": "产品兼容性事实",
                "db_table": "product_compatibility",
                "unique_together": {
                    ("source_product", "target_product", "compatibility")
                },
            },
        ),
        migrations.CreateModel(
            name="ProductMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("reagent", "试剂"),
                            ("buffer", "缓冲液"),
                            ("control", "对照"),
                            ("enzyme", "酶"),
                            ("label", "标记物"),
                            ("solvent", "溶剂"),
                            ("other", "其他"),
                        ],
                        default="reagent",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("curated", "人工审核"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="证据等级",
                    ),
                ),
                ("display_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_methods",
                        to="knowledge.method",
                        verbose_name="方法",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_methods",
                        to="commerce.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品-方法关联",
                "verbose_name_plural": "产品-方法关联",
                "db_table": "product_method",
                "indexes": [
                    models.Index(
                        fields=["method", "display_order"],
                        name="product_method_order_idx",
                    )
                ],
                "unique_together": {("product", "method", "role")},
            },
        ),
        migrations.CreateModel(
            name="ProductProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("substitute", "替代品"),
                            ("complement", "互补品"),
                            ("alternate", "替代方案"),
                            ("bundle", "捆绑销售"),
                            ("related", "相关产品"),
                        ],
                        default="related",
                        max_length=20,
                        verbose_name="关系类型",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("one_way", "单向"), ("bidirectional", "双向")],
                        default="bidirectional",
                        max_length=20,
                        verbose_name="方向",
                    ),
                ),
                ("strength", models.IntegerField(default=0, verbose_name="关联强度")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "source_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_relations_as_source",
                        to="commerce.product",
                        verbose_name="源产品",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_relations_as_target",
                        to="commerce.product",
                        verbose_name="目标产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品-产品关系",
                "verbose_name_plural": "产品-产品关系",
                "db_table": "product_product",
                "unique_together": {
                    ("source_product", "target_product", "relation_type")
                },
            },
        ),
        migrations.CreateModel(
            name="ProductReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "citation_role",
                    models.CharField(
                        choices=[
                            ("primary", "主要引用"),
                            ("supporting", "支持性引用"),
                            ("validation", "验证引用"),
                            ("background", "背景引用"),
                        ],
                        default="supporting",
                        max_length=20,
                        verbose_name="引用角色",
                    ),
                ),
                ("display_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_references",
                        to="commerce.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_references",
                        to="knowledge.reference",
                        verbose_name="文献",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品-文献关联",
                "verbose_name_plural": "产品-文献关联",
                "db_table": "product_reference",
                "indexes": [
                    models.Index(
                        fields=["product", "display_order"],
                        name="product_ref_order_idx",
                    )
                ],
                "unique_together": {("product", "reference", "citation_role")},
            },
        ),
    ]
