# Generated by Django 5.1.3 on 2026-08-06 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
        ('commerce', '0010_product_archived_auditlog'),
        ('knowledge', '0011_alter_reference_doi_alter_reference_pmid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('relevance_score', models.FloatField(db_index=True, default=0.0, verbose_name='相关性总分')),
                ('score_a', models.FloatField(blank=True, null=True, verbose_name='轴A 厂商声称')),
                ('score_b', models.FloatField(blank=True, null=True, verbose_name='轴B 文献实证')),
                ('score_c', models.FloatField(blank=True, null=True, verbose_name='轴C 语义')),
                ('literature_count', models.IntegerField(default=0, verbose_name='对齐文献数')),
                ('relevance_basis', models.CharField(blank=True, default='', max_length=32, verbose_name='相关性依据')),
                ('link_source', models.CharField(choices=[('explicit', '显式关联'), ('inherited', '派生关联'), ('auto', '自动匹配')], default='inherited', max_length=16, verbose_name='来源')),
                ('tier', models.CharField(choices=[('document', '文档相关'), ('literature', '文献支持'), ('featured', '编辑精选')], default='featured', max_length=16, verbose_name='档位')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='计算时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_links', to='commerce.product', verbose_name='产品')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_protocols', to='knowledge.protocol', verbose_name='协议')),
            ],
            options={
                'verbose_name': '产品-协议相关性',
                'verbose_name_plural': '产品-协议相关性',
                'db_table': 'product_protocol',
                'indexes': [models.Index(fields=['product', 'relevance_score'], name='product_proto_score_idx'), models.Index(fields=['product', 'tier'], name='product_proto_tier_idx')],
                'unique_together': {('product', 'protocol')},
            },
        ),
    ]
