# Generated by Django 5.1.3 on 2026-08-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0002_productprotocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodprotocol',
            name='explicit',
            field=models.BooleanField(default=False, help_text='研究者显式建立的跨方法合法关联；清理命令不删除 explicit=True 的残留', verbose_name='显式关联'),
        ),
    ]
