# Generated by Django 5.1.3 on 2026-08-24 04:14

import apps.bridges.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0005_methodprotocol_evidence_source'),
        ('commerce', '0013_product_substructure_tags'),
        ('knowledge', '0020_reagentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodReagentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dependency_type', models.CharField(choices=[('essential', 'essential'), ('enabling', 'enabling'), ('optional', 'optional')], db_index=True, max_length=12, verbose_name='依赖类型')),
                ('scope', models.CharField(choices=[('canonical', 'canonical'), ('common', 'common'), ('conditional', 'conditional')], db_index=True, default='common', max_length=12, verbose_name='适用范围')),
                ('dependency_group', models.CharField(blank=True, db_index=True, default='', help_text='同 method+group 内多 RC = 可替代实现集合（OR，须 same dependency_type，RC-11）；""=ungrouped', max_length=60, verbose_name='功能依赖组')),
                ('evidence_type', models.CharField(choices=[('method_definition', 'method_definition'), ('protocol', 'protocol'), ('literature', 'literature'), ('manufacturer', 'manufacturer'), ('curated_inference', 'curated_inference')], default='curated_inference', max_length=24, verbose_name='证据类型')),
                ('evidence_reference', models.JSONField(blank=True, default=list, help_text='[{type: PMID|DOI|PROTOCOL|MANUFACTURER|DOC, value}]', validators=[apps.bridges.models.validate_evidence_reference], verbose_name='证据引用')),
                ('evidence_strength', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=6, verbose_name='证据强度')),
                ('evidence_note', models.TextField(blank=True, default='', verbose_name='证据说明')),
                ('curator', models.CharField(blank=True, default='', max_length=100, verbose_name='策展人')),
                ('status', models.CharField(choices=[('curated', 'curated'), ('pending_review', 'pending_review'), ('deprecated', 'deprecated')], default='curated', max_length=20, verbose_name='状态')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagent_classes', to='knowledge.method', verbose_name='方法')),
                ('reagent_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methods', to='knowledge.reagentclass', verbose_name='试剂类')),
            ],
            options={
                'verbose_name': '方法-试剂类依赖',
                'verbose_name_plural': '方法-试剂类依赖',
                'db_table': 'method_reagent_class',
                'indexes': [models.Index(fields=['method', 'dependency_group'], name='idx_mrc_method_group')],
                'constraints': [models.UniqueConstraint(fields=('method', 'reagent_class'), name='uq_mrc_method_rc'), models.CheckConstraint(condition=models.Q(models.Q(('scope', 'conditional'), _negated=True), models.Q(('dependency_type', 'essential'), _negated=True), _connector='OR'), name='ck_mrc_conditional_not_essential')],
            },
        ),
        migrations.CreateModel(
            name='ProductMethodRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('relation_type', models.CharField(choices=[('derived_relevance', 'derived_relevance'), ('verified_applicability', 'verified_applicability')], db_index=True, max_length=24, verbose_name='关系类型')),
                ('evidence_type', models.CharField(blank=True, default='', max_length=24, verbose_name='证据类型')),
                ('evidence_reference', models.JSONField(blank=True, default=None, null=True, validators=[apps.bridges.models.validate_evidence_reference], verbose_name='证据引用')),
                ('evidence_strength', models.CharField(blank=True, default='', max_length=6, verbose_name='证据强度')),
                ('evidence_note', models.TextField(blank=True, default='', verbose_name='证据说明')),
                ('curator', models.CharField(blank=True, default='', max_length=100, verbose_name='策展人')),
                ('status', models.CharField(choices=[('active', 'active'), ('review', 'review'), ('deprecated', 'deprecated')], default='active', max_length=20, verbose_name='状态')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_relations', to='knowledge.method', verbose_name='方法')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='method_relations', to='commerce.product', verbose_name='产品')),
                ('source_reagent_class', models.ForeignKey(blank=True, help_text='derived 必填（主路径解释）；verified 必须 NULL（PMR-01）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='method_relation_explanations', to='knowledge.reagentclass', verbose_name='来源试剂类')),
            ],
            options={
                'verbose_name': '产品-方法关系',
                'verbose_name_plural': '产品-方法关系',
                'db_table': 'product_method_relation',
                'indexes': [models.Index(fields=['product', 'relation_type'], name='idx_pmr_product_rt'), models.Index(fields=['method', 'relation_type'], name='idx_pmr_method_rt')],
                'constraints': [models.UniqueConstraint(fields=('product', 'method', 'relation_type'), name='uq_pmr_product_method_relation_type'), models.CheckConstraint(condition=models.Q(models.Q(('relation_type', 'derived_relevance'), ('source_reagent_class__isnull', False), ('evidence_type', ''), ('evidence_reference__isnull', True), ('evidence_strength', '')), models.Q(('relation_type', 'verified_applicability'), ('source_reagent_class__isnull', True), models.Q(('evidence_type', ''), _negated=True), ('evidence_reference__isnull', False), models.Q(('evidence_strength', ''), _negated=True)), _connector='OR'), name='ck_pmr_relation_discriminator')],
            },
        ),
        migrations.CreateModel(
            name='ProductReagentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignment_type', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('conditional', 'conditional')], default='primary', max_length=12, verbose_name='分类角色')),
                ('classification_method', models.CharField(choices=[('rule', 'rule'), ('ai', 'ai'), ('manual', 'manual')], default='rule', max_length=8, verbose_name='分类方法')),
                ('classification_rule', models.CharField(blank=True, db_index=True, default='', help_text='如 nucleotide.cy5_dutp；规则标识符，不唯一（同规则应用于多产品）', max_length=100, verbose_name='分类规则 ID')),
                ('classification_rule_version', models.CharField(blank=True, default='', help_text='auto_accepted 必须引用 registry 中 threshold_passed=true 的版本', max_length=20, verbose_name='分类规则版本')),
                ('confidence', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='medium', help_text='规则/模型置信度，≠科学有效性（RC-04）', max_length=6, verbose_name='置信度')),
                ('evidence', models.TextField(blank=True, default='', help_text='解释文本；assignment_type=conditional 时必填（RC-08）', verbose_name='分类证据')),
                ('curator', models.CharField(blank=True, default='', max_length=100, verbose_name='策展人')),
                ('status', models.CharField(choices=[('candidate', 'candidate'), ('pending_review', 'pending_review'), ('auto_accepted', 'auto_accepted'), ('human_verified', 'human_verified'), ('rejected', 'rejected'), ('deprecated', 'deprecated')], db_index=True, default='pending_review', help_text='RC-10：未过阈值验证前不得 auto_accepted', max_length=20, verbose_name='状态')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reagent_classes', to='commerce.product', verbose_name='产品')),
                ('reagent_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='knowledge.reagentclass', verbose_name='试剂类')),
            ],
            options={
                'verbose_name': '产品-试剂类分类',
                'verbose_name_plural': '产品-试剂类分类',
                'db_table': 'product_reagent_class',
                'indexes': [models.Index(fields=['product'], name='idx_prc_product'), models.Index(fields=['reagent_class'], name='idx_prc_rc')],
                'constraints': [models.UniqueConstraint(fields=('product', 'reagent_class'), name='uq_prc_product_rc'), models.CheckConstraint(condition=models.Q(models.Q(('assignment_type', 'conditional'), _negated=True), models.Q(('evidence__isnull', False), models.Q(('evidence', ''), _negated=True)), _connector='OR'), name='ck_prc_conditional_requires_evidence')],
            },
        ),
    ]
