# Generated by Django 5.1.3 on 2026-08-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0006_methodreagentclass_productmethodrelation_and_more'),
        ('commerce', '0013_product_substructure_tags'),
        ('knowledge', '0020_reagentclass'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productmethodrelation',
            name='ck_pmr_relation_discriminator',
        ),
        migrations.AlterField(
            model_name='productmethodrelation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('review', 'review'), ('deprecated', 'deprecated'), ('rejected', 'rejected')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AddConstraint(
            model_name='productmethodrelation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('relation_type', 'derived_relevance'), _negated=True), models.Q(('source_reagent_class__isnull', False), ('evidence_type', ''), ('evidence_reference__isnull', True), ('evidence_strength', '')), _connector='OR'), models.Q(models.Q(('relation_type', 'verified_applicability'), ('status', 'active'), _negated=True), models.Q(('source_reagent_class__isnull', True), models.Q(('evidence_type', ''), _negated=True), ('evidence_reference__isnull', False), models.Q(('evidence_strength', ''), _negated=True)), _connector='OR')), name='ck_pmr_relation_discriminator'),
        ),
    ]
