# Generated by Django 5.1.3 on 2026-06-11 05:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "活跃"),
                            ("deprecated", "已弃用"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="摘要"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "应用场景",
                "verbose_name_plural": "应用场景",
                "db_table": "application",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Compatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "活跃"),
                            ("deprecated", "已弃用"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="规则编码"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("product-product", "产品-产品"),
                            ("product-method", "产品-方法"),
                            ("product-protocol", "产品-协议"),
                            ("product-instrument", "产品-仪器"),
                        ],
                        max_length=30,
                        verbose_name="适用范围",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("compatible", "兼容"),
                            ("incompatible", "不兼容"),
                            ("conditional", "条件兼容"),
                            ("warning", "警告"),
                        ],
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("warning", "警告"),
                            ("blocking", "阻断"),
                            ("critical", "严重"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "expression_json",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="规则表达式(JSON)"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="规则摘要"),
                ),
            ],
            options={
                "verbose_name": "兼容性规则",
                "verbose_name_plural": "兼容性规则",
                "db_table": "compatibility",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                (
                    "authors",
                    models.TextField(blank=True, default="", verbose_name="作者"),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="期刊"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(blank=True, null=True, verbose_name="年份"),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "pmid",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="PMID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="URL"
                    ),
                ),
                (
                    "citation_text",
                    models.TextField(blank=True, default="", verbose_name="引用文本"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("journal", "期刊论文"),
                            ("book", "书籍"),
                            ("patent", "专利"),
                            ("thesis", "学位论文"),
                            ("web", "网页"),
                            ("other", "其他"),
                        ],
                        default="journal",
                        max_length=20,
                        verbose_name="来源类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "参考文献",
                "verbose_name_plural": "参考文献",
                "db_table": "reference",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResearchGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "活跃"),
                            ("deprecated", "已弃用"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="摘要"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(9999)],
                        verbose_name="优先级",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究目标",
                "verbose_name_plural": "研究目标",
                "db_table": "research_goal",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "活跃"),
                            ("deprecated", "已弃用"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="摘要"),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, default="", verbose_name="用途"),
                ),
                (
                    "advantages",
                    models.TextField(blank=True, default="", verbose_name="优势"),
                ),
                (
                    "limitations",
                    models.TextField(blank=True, default="", verbose_name="局限性"),
                ),
                (
                    "cost_band",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="成本区间"
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="时间线"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="knowledge.application",
                        verbose_name="应用场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "科研方法",
                "verbose_name_plural": "科研方法",
                "db_table": "method",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "活跃"),
                            ("deprecated", "已弃用"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("slug", models.SlugField(max_length=255, verbose_name="Slug")),
                (
                    "version",
                    models.CharField(
                        default="1.0", max_length=50, verbose_name="版本号"
                    ),
                ),
                (
                    "objective",
                    models.TextField(blank=True, default="", verbose_name="目标"),
                ),
                (
                    "principle",
                    models.TextField(blank=True, default="", verbose_name="原理"),
                ),
                (
                    "materials",
                    models.TextField(blank=True, default="", verbose_name="材料"),
                ),
                (
                    "reagents",
                    models.TextField(blank=True, default="", verbose_name="试剂"),
                ),
                (
                    "equipment",
                    models.TextField(blank=True, default="", verbose_name="设备"),
                ),
                (
                    "troubleshooting",
                    models.TextField(blank=True, default="", verbose_name="故障排除"),
                ),
                (
                    "expected_results",
                    models.TextField(blank=True, default="", verbose_name="预期结果"),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True, default="", verbose_name="参考文献文本"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "superseded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="取代时间"
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocols",
                        to="knowledge.method",
                        verbose_name="方法",
                    ),
                ),
            ],
            options={
                "verbose_name": "实验协议",
                "verbose_name_plural": "实验协议",
                "db_table": "protocol",
                "ordering": ["method", "-version"],
                "unique_together": {("method", "slug", "version")},
            },
        ),
        migrations.AddField(
            model_name="application",
            name="research_goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="knowledge.researchgoal",
                verbose_name="研究目标",
            ),
        ),
        migrations.CreateModel(
            name="ProtocolStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("step_no", models.PositiveIntegerField(verbose_name="步骤序号")),
                ("title", models.CharField(max_length=255, verbose_name="步骤标题")),
                (
                    "body",
                    models.TextField(blank=True, default="", verbose_name="步骤内容"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预计时长(秒)"
                    ),
                ),
                (
                    "warnings",
                    models.TextField(blank=True, default="", verbose_name="注意事项"),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="knowledge.protocol",
                        verbose_name="协议",
                    ),
                ),
            ],
            options={
                "verbose_name": "协议步骤",
                "verbose_name_plural": "协议步骤",
                "db_table": "protocol_step",
                "ordering": ["protocol", "step_no"],
                "indexes": [
                    models.Index(
                        fields=["protocol", "step_no"], name="protocol_step_idx"
                    )
                ],
                "unique_together": {("protocol", "step_no")},
            },
        ),
    ]
