# Generated by Django 5.1.3 on 2026-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="method",
            index=models.Index(fields=["slug"], name="method_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="protocol",
            index=models.Index(fields=["slug"], name="protocol_slug_idx"),
        ),
    ]
