# Generated by Django 5.1.3 on 2026-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocolstep",
            name="required_materials",
            field=models.TextField(blank=True, default="", verbose_name="所需材料"),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("published", "已发布"),
                    ("superseded", "已取代"),
                    ("archived", "已归档"),
                ],
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
