# Generated by Django 5.1.3 on 2026-06-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0003_protocolstep_required_materials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="display_priority",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="展示优先级"
            ),
        ),
    ]
