# Generated by Django 5.1.3 on 2026-06-25 09:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_method_display_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(
                help_text="具体实验场景，例如：RNA Fluorescent Labeling, Sanger Sequencing",
                max_length=255,
                verbose_name="名称",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="research_goal",
            field=models.ForeignKey(
                help_text="这个应用属于哪个研究方向",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="knowledge.researchgoal",
                verbose_name="研究目标",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="描述这个实验场景的原理和用途",
                verbose_name="摘要",
            ),
        ),
        migrations.AlterField(
            model_name="compatibility",
            name="code",
            field=models.CharField(
                help_text="唯一编码，例如：COMP-PM-001",
                max_length=100,
                unique=True,
                verbose_name="规则编码",
            ),
        ),
        migrations.AlterField(
            model_name="compatibility",
            name="expression_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON 格式的规则条件，例如：{"min_purity": 95, "temp_range": [-20, 4]}',
                verbose_name="规则表达式(JSON)",
            ),
        ),
        migrations.AlterField(
            model_name="compatibility",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("compatible", "兼容"),
                    ("incompatible", "不兼容"),
                    ("conditional", "条件兼容"),
                    ("warning", "警告"),
                ],
                help_text="兼容/不兼容/条件兼容/警告",
                max_length=20,
                verbose_name="规则类型",
            ),
        ),
        migrations.AlterField(
            model_name="compatibility",
            name="scope",
            field=models.CharField(
                choices=[
                    ("product-product", "产品-产品"),
                    ("product-method", "产品-方法"),
                    ("product-protocol", "产品-协议"),
                    ("product-instrument", "产品-仪器"),
                ],
                help_text="这条规则适用于哪类实体关系",
                max_length=30,
                verbose_name="适用范围",
            ),
        ),
        migrations.AlterField(
            model_name="compatibility",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "信息"),
                    ("warning", "警告"),
                    ("blocking", "阻断"),
                    ("critical", "严重"),
                ],
                default="info",
                help_text="违反此规则的严重程度",
                max_length=20,
                verbose_name="严重程度",
            ),
        ),
        migrations.AlterField(
            model_name="compatibility",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="用自然语言描述这条规则",
                verbose_name="规则摘要",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="advantages",
            field=models.TextField(
                blank=True,
                default="",
                help_text="每条优势一行，例如：高特异性、快速反应、生物正交",
                verbose_name="优势",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="application",
            field=models.ForeignKey(
                help_text="这个方法属于哪个实验场景",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="methods",
                to="knowledge.application",
                verbose_name="应用场景",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="cost_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low", "低成本 (<$50/sample)"),
                    ("medium", "中等 ($50-200/sample)"),
                    ("high", "高成本 (>$200/sample)"),
                    ("", "未确定"),
                ],
                default="",
                help_text="每次实验的大致成本范围",
                max_length=100,
                verbose_name="成本区间",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="limitations",
            field=models.TextField(
                blank=True,
                default="",
                help_text="每条局限一行，例如：需要铜催化剂、对活细胞有毒",
                verbose_name="局限性",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="name",
            field=models.CharField(
                help_text="技术方法名称，例如：CuAAC Click Chemistry, NHS-Ester Conjugation",
                max_length=255,
                verbose_name="名称",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="purpose",
            field=models.TextField(
                blank=True,
                default="",
                help_text="这个方法具体能做什么",
                verbose_name="用途",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="一句话描述方法原理",
                verbose_name="摘要",
            ),
        ),
        migrations.AlterField(
            model_name="method",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minutes", "几分钟 (<30 min)"),
                    ("hours", "数小时 (30 min - 4 hours)"),
                    ("days", "数天 (1-7 days)"),
                    ("weeks", "数周 (>1 week)"),
                    ("", "未确定"),
                ],
                default="",
                help_text="完成一次实验所需的大致时间",
                max_length=100,
                verbose_name="时间线",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="equipment",
            field=models.TextField(
                blank=True, default="", help_text="所需设备列表", verbose_name="设备"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="expected_results",
            field=models.TextField(
                blank=True,
                default="",
                help_text="成功执行后应观察到的结果",
                verbose_name="预期结果",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="materials",
            field=models.TextField(
                blank=True,
                default="",
                help_text="所需材料列表，每行一个",
                verbose_name="材料",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="method",
            field=models.ForeignKey(
                help_text="这个协议基于哪个技术方法",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="protocols",
                to="knowledge.method",
                verbose_name="方法",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="name",
            field=models.CharField(
                help_text="协议全名，例如：CuAAC RNA Fluorescent Labeling Protocol",
                max_length=255,
                verbose_name="名称",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="objective",
            field=models.TextField(
                blank=True,
                default="",
                help_text="这个协议要达成什么目的",
                verbose_name="目标",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="principle",
            field=models.TextField(
                blank=True, default="", help_text="实验原理简述", verbose_name="原理"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="reagents",
            field=models.TextField(
                blank=True,
                default="",
                help_text="所需试剂列表，包含浓度和用量",
                verbose_name="试剂",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="references",
            field=models.TextField(
                blank=True,
                default="",
                help_text="引用的论文，每行一条（PMID 或 DOI）",
                verbose_name="参考文献文本",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="troubleshooting",
            field=models.TextField(
                blank=True,
                default="",
                help_text="常见问题和解决方案",
                verbose_name="故障排除",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="version",
            field=models.CharField(
                default="1.0",
                help_text="协议版本，例如：1.0, 2.1",
                max_length=50,
                verbose_name="版本号",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="详细操作描述",
                verbose_name="步骤内容",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="duration_seconds",
            field=models.IntegerField(
                blank=True,
                help_text="预计耗时，单位秒（例如 1800 = 30分钟）",
                null=True,
                verbose_name="预计时长(秒)",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="protocol",
            field=models.ForeignKey(
                help_text="所属协议",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="knowledge.protocol",
                verbose_name="协议",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="required_materials",
            field=models.TextField(
                blank=True,
                default="",
                help_text="本步骤需要的特定材料",
                verbose_name="所需材料",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="step_no",
            field=models.PositiveIntegerField(
                help_text="步骤编号，从 1 开始", verbose_name="步骤序号"
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="title",
            field=models.CharField(
                help_text="简短标题，例如：准备反应液、纯化产物",
                max_length=255,
                verbose_name="步骤标题",
            ),
        ),
        migrations.AlterField(
            model_name="protocolstep",
            name="warnings",
            field=models.TextField(
                blank=True,
                default="",
                help_text="安全提示和注意事项",
                verbose_name="注意事项",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="authors",
            field=models.TextField(
                blank=True,
                default="",
                help_text="作者列表，用逗号分隔",
                verbose_name="作者",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="citation_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="标准引用格式文本",
                verbose_name="引用文本",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="doi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="数字对象标识符，例如：10.1038/s41586-024-12345-6",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="DOI",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="journal",
            field=models.CharField(
                blank=True,
                default="",
                help_text="期刊名称，例如：Nature Protocols, Chemical Reviews",
                max_length=255,
                verbose_name="期刊",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="pmid",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PubMed ID，例如：38123456",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="PMID",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("journal", "期刊论文"),
                    ("book", "书籍"),
                    ("patent", "专利"),
                    ("thesis", "学位论文"),
                    ("web", "网页"),
                    ("other", "其他"),
                ],
                default="journal",
                help_text="文献类型",
                max_length=20,
                verbose_name="来源类型",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="title",
            field=models.CharField(
                help_text="论文/文献完整标题", max_length=500, verbose_name="标题"
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="文献链接",
                max_length=500,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="year",
            field=models.IntegerField(
                blank=True,
                help_text="发表年份，例如：2024",
                null=True,
                verbose_name="年份",
            ),
        ),
        migrations.AlterField(
            model_name="researchgoal",
            name="name",
            field=models.CharField(
                help_text="研究方向名称，例如：RNA Analysis, DNA Sequencing, Click Chemistry",
                max_length=255,
                verbose_name="名称",
            ),
        ),
        migrations.AlterField(
            model_name="researchgoal",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="数字越大越靠前，0 为默认排序",
                validators=[django.core.validators.MaxValueValidator(9999)],
                verbose_name="优先级",
            ),
        ),
        migrations.AlterField(
            model_name="researchgoal",
            name="slug",
            field=models.SlugField(
                help_text="URL 友好的标识符，自动生成",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="researchgoal",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="一句话描述这个研究方向的核心内容",
                verbose_name="摘要",
            ),
        ),
    ]
