# Generated by Django 5.1.3 on 2026-07-10 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_application_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='research_goal',
            field=models.ForeignKey(blank=True, help_text='这个应用属于哪个研究方向', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='knowledge.researchgoal', verbose_name='研究目标'),
        ),
        migrations.AlterField(
            model_name='method',
            name='application',
            field=models.ForeignKey(blank=True, help_text='这个方法属于哪个实验场景', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='knowledge.application', verbose_name='应用场景'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='method',
            field=models.ForeignKey(blank=True, help_text='这个协议基于哪个技术方法', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='knowledge.method', verbose_name='方法'),
        ),
    ]
