# Generated by Django 5.1.3 on 2026-08-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_translate_knowledge_to_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(blank=True, help_text='数字对象标识符，例如：10.1038/s41586-024-12345-6', max_length=100, null=True, unique=True, verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='pmid',
            field=models.CharField(blank=True, help_text='PubMed ID，例如：38123456', max_length=50, null=True, unique=True, verbose_name='PMID'),
        ),
    ]
