# Generated by Django 5.1.3 on 2026-08-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0011_alter_reference_doi_alter_reference_pmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='source',
            field=models.CharField(blank=True, choices=[('curated', '人工策展库'), ('bioprocorpus', 'BioProCorpus 自动匹配库')], default='curated', help_text='协议来源：curated=人工策展库；bioprocorpus=BioProCorpus 自动匹配库', max_length=32, verbose_name='来源'),
        ),
    ]
