# Generated by Django 5.1.3 on 2026-08-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_protocol_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_test_fixture',
            field=models.BooleanField(db_index=True, default=False, help_text='True 表示此行由自动化测试残留产生，不参与任何对外展示与统计；仅作标记，数据不会被删除', verbose_name='测试夹具'),
        ),
        migrations.AddField(
            model_name='method',
            name='is_test_fixture',
            field=models.BooleanField(db_index=True, default=False, help_text='True 表示此行由自动化测试残留产生，不参与任何对外展示与统计；仅作标记，数据不会被删除', verbose_name='测试夹具'),
        ),
        migrations.AddField(
            model_name='researchgoal',
            name='is_test_fixture',
            field=models.BooleanField(db_index=True, default=False, help_text='True 表示此行由自动化测试残留产生，不参与任何对外展示与统计；仅作标记，数据不会被删除', verbose_name='测试夹具'),
        ),
    ]
