# Generated by Django 5.1.3 on 2026-08-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0013_application_is_test_fixture_method_is_test_fixture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgoal',
            name='protocols',
            field=models.ManyToManyField(blank=True, help_text='研究者人工策展纳入该研究目标的协议集合（无数据驱动，仅策展）', related_name='research_goals', to='knowledge.protocol', verbose_name='策展协议集'),
        ),
        migrations.CreateModel(
            name='FacetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('facet_type', models.CharField(choices=[('technique', '实验技术'), ('biological_context', '物种/细胞/疾病'), ('study_type', '研究类型')], db_index=True, max_length=32, verbose_name='facet 维度')),
                ('kind', models.CharField(blank=True, choices=[('species', '物种'), ('cell', '细胞'), ('disease', '疾病')], db_index=True, default='', help_text='仅 biological_context 维度使用：species / cell / disease', max_length=16, verbose_name='biological_context 子类型')),
                ('value', models.CharField(help_text='受控词表项英文名称，例如：PCR / qPCR、Mus musculus、Cancer / Tumor Model', max_length=255, verbose_name='facet 值(英文)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
            ],
            options={
                'verbose_name': '受控词表项',
                'verbose_name_plural': '受控词表项',
                'db_table': 'facet_value',
                'ordering': ['facet_type', 'kind', 'value'],
                'unique_together': {('facet_type', 'kind', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProtocolFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('source', models.CharField(choices=[('cluster_main', '聚类主标签'), ('cross_detect', '交叉检测补标')], default='cluster_main', max_length=16, verbose_name='来源')),
                ('facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_facets', to='knowledge.facetvalue', verbose_name='facet')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_facets', to='knowledge.protocol', verbose_name='协议')),
            ],
            options={
                'verbose_name': '协议-facet 关联',
                'verbose_name_plural': '协议-facet 关联',
                'db_table': 'protocol_facet',
            },
        ),
        migrations.AddField(
            model_name='protocol',
            name='facets',
            field=models.ManyToManyField(blank=True, help_text='协议的类型化 facet 标签（technique / biological_context / study_type），无打分', related_name='protocols', through='knowledge.ProtocolFacet', to='knowledge.facetvalue', verbose_name='受控词表标签'),
        ),
        migrations.AddIndex(
            model_name='protocolfacet',
            index=models.Index(fields=['protocol', 'source'], name='protocol_facet_src_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolfacet',
            unique_together={('protocol', 'facet')},
        ),
    ]
