# Generated by Django 5.1.3 on 2026-08-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0014_researchgoal_protocols_facetvalue_protocolfacet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facetvalue',
            name='facet_type',
            field=models.CharField(choices=[('application', '研究域'), ('method', '方法'), ('biological_context', '物种/细胞/疾病'), ('study_type', '研究类型')], db_index=True, max_length=32, verbose_name='facet 维度'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='facets',
            field=models.ManyToManyField(blank=True, help_text='协议的类型化 facet 标签（application / method / biological_context / study_type），无打分', related_name='protocols', through='knowledge.ProtocolFacet', to='knowledge.facetvalue', verbose_name='受控词表标签'),
        ),
    ]
