# Generated by Django 5.1.3 on 2026-08-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_flip_technique_to_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['-version'], 'verbose_name': '实验协议', 'verbose_name_plural': '实验协议'},
        ),
        migrations.AlterUniqueTogether(
            name='protocol',
            unique_together={('slug', 'version')},
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='method',
        ),
    ]
