# Generated by Django 5.1.3 on 2026-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_method_add_topchain_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgoal',
            name='application_collection',
            field=models.ManyToManyField(blank=True, help_text='该研究目标覆盖的技术族集合（策展，M:N；一个技术族可服务多个研究目标）', related_name='research_goal_collections', to='knowledge.application', verbose_name='策展技术族集合'),
        ),
    ]
