# Generated by Django 5.1.3 on 2026-08-24 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_researchgoal_applications_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id_code', models.CharField(help_text='RC-01…RC-33/19A/19B/20A/20B；ontology identifier（不可变）', max_length=20, unique=True, verbose_name='Ontology ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('slug', models.SlugField(help_text='URL/display identifier（技术上可改，不作 ontology 身份）', max_length=200, unique=True, verbose_name='Slug')),
                ('definition', models.TextField(blank=True, default='', verbose_name='定义')),
                ('behavior_type', models.CharField(choices=[('method_specific', 'method_specific'), ('method_enabling', 'method_enabling'), ('context_dependent', 'context_dependent')], db_index=True, help_text='method_specific：天然强 Method 指向；method_enabling：可支持多 Method；context_dependent：须结合 Product/Protocol 上下文', max_length=20, verbose_name='行为性质')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('approved', 'approved'), ('deprecated', 'deprecated')], db_index=True, default='approved', max_length=20, verbose_name='状态')),
                ('is_test_fixture', models.BooleanField(db_index=True, default=False, help_text='True 表示此行由自动化测试残留产生，不参与任何对外展示与统计；仅作标记，数据不会被删除', verbose_name='测试夹具')),
                ('replaced_from', models.ForeignKey(blank=True, help_text='仅记录 ontology lineage（如 19A/19B ← RC-19）；不自动继承任何关系（RC-06）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='knowledge.reagentclass', verbose_name='替代来源')),
            ],
            options={
                'verbose_name': '试剂类',
                'verbose_name_plural': '试剂类',
                'db_table': 'reagent_class',
                'ordering': ['id_code'],
            },
        ),
    ]
