# Generated by Django 5.1.3 on 2026-08-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0020_reagentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='origin',
            field=models.CharField(choices=[('human_curated', '人工策展'), ('ai_extracted', 'AI 从协议提取'), ('imported', '存量导入')], default='imported', help_text='human_curated=人工策展 / ai_extracted=AI 从协议提取 / imported=存量导入（默认，不猜来源）', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='application',
            name='origin_detail',
            field=models.CharField(blank=True, default='', help_text='溯源详情，如 extractor_v0.1|protocols:12,34,56 或 reviewed_by:admin', max_length=500, verbose_name='来源详情'),
        ),
        migrations.AddField(
            model_name='method',
            name='origin',
            field=models.CharField(choices=[('human_curated', '人工策展'), ('ai_extracted', 'AI 从协议提取'), ('imported', '存量导入')], default='imported', help_text='human_curated=人工策展 / ai_extracted=AI 从协议提取 / imported=存量导入（默认，不猜来源）', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='method',
            name='origin_detail',
            field=models.CharField(blank=True, default='', help_text='溯源详情，如 extractor_v0.1|protocols:12,34,56 或 reviewed_by:admin', max_length=500, verbose_name='来源详情'),
        ),
        migrations.AddField(
            model_name='researchgoal',
            name='origin',
            field=models.CharField(choices=[('human_curated', '人工策展'), ('ai_extracted', 'AI 从协议提取'), ('imported', '存量导入')], default='imported', help_text='human_curated=人工策展 / ai_extracted=AI 从协议提取 / imported=存量导入（默认，不猜来源）', max_length=20, verbose_name='数据来源'),
        ),
        migrations.AddField(
            model_name='researchgoal',
            name='origin_detail',
            field=models.CharField(blank=True, default='', help_text='溯源详情，如 extractor_v0.1|protocols:12,34,56 或 reviewed_by:admin', max_length=500, verbose_name='来源详情'),
        ),
    ]
