# Generated by Django 5.1.3 on 2026-06-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_alternate_email_user_avatar_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_payment_method",
            field=models.CharField(
                blank=True,
                default="purchase_order",
                max_length=20,
                verbose_name="默认付款方式",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_po_number",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="默认PO号"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="收件邮箱"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="收件人"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_phone",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="收件电话"
            ),
        ),
    ]
