# Generated by Django 5.1.3 on 2026-07-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_default_payment_method_user_default_po_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('other', 'Other')], default='shipping', max_length=20)),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('attention', models.CharField(blank=True, default='', max_length=200, verbose_name='收件人/部门')),
                ('line1', models.CharField(blank=True, default='', max_length=200, verbose_name='地址行1')),
                ('line2', models.CharField(blank=True, default='', max_length=200, verbose_name='地址行2')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='城市')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='州/省')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='邮编')),
                ('country', models.CharField(default='US', max_length=100, verbose_name='国家')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='电话')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.organization', verbose_name='机构')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
                'db_table': 'address',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization', 'type'), name='unique_default_address_per_type')],
            },
        ),
    ]
