# Generated by Django 5.1.3 on 2026-08-04 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_translate_org_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='注册后须点击验证邮件中的链接置为 True，方可登录。', verbose_name='邮箱已验证'),
        ),
        # Backfill: every account that already existed before this feature was
        # introduced could log in previously, so treat them as already-verified.
        # New registrations are set to False explicitly in RegisterSerializer.
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('accounts', 'User')
            .objects.update(email_verified=True),
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '邮箱验证令牌',
                'verbose_name_plural': '邮箱验证令牌',
                'db_table': 'email_verification',
            },
        ),
    ]
