# Generated by Django 5.1.3 on 2026-06-11 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "locale",
                    models.CharField(default="en", max_length=20, verbose_name="语言"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="是否激活")),
            ],
            options={
                "verbose_name": "目录分组",
                "verbose_name_plural": "目录分组",
                "db_table": "catalog_group",
            },
        ),
        migrations.CreateModel(
            name="ProductClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="分类名称")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="commerce.productclass",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品分类",
                "verbose_name_plural": "产品分类",
                "db_table": "product_class",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "活跃"),
                            ("deprecated", "已弃用"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="产品名称")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "cas",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="CAS号"
                    ),
                ),
                (
                    "smiles",
                    models.TextField(blank=True, default="", verbose_name="SMILES"),
                ),
                (
                    "synonyms",
                    models.JSONField(blank=True, default=list, verbose_name="同义词"),
                ),
                (
                    "inchi",
                    models.TextField(blank=True, default="", verbose_name="InChI"),
                ),
                (
                    "purity",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="纯度"
                    ),
                ),
                (
                    "storage",
                    models.TextField(blank=True, default="", verbose_name="储存条件"),
                ),
                (
                    "shipping",
                    models.TextField(blank=True, default="", verbose_name="运输条件"),
                ),
                (
                    "lead_time",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="货期"
                    ),
                ),
                (
                    "handling_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="操作注意事项"
                    ),
                ),
                (
                    "shelf_life",
                    models.DurationField(blank=True, null=True, verbose_name="保质期"),
                ),
                (
                    "research_use_only",
                    models.BooleanField(default=True, verbose_name="仅限研究用途"),
                ),
                (
                    "catalog_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="commerce.cataloggroup",
                        verbose_name="目录分组",
                    ),
                ),
                (
                    "product_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="commerce.productclass",
                        verbose_name="产品分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
                "db_table": "product",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "sku_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="SKU编码"
                    ),
                ),
                (
                    "pack_size",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="包装规格"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="价格"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=10, verbose_name="币种"),
                ),
                (
                    "inventory_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "现货"),
                            ("limited", "少量"),
                            ("preorder", "预订"),
                            ("out_of_stock", "缺货"),
                        ],
                        default="in_stock",
                        max_length=20,
                        verbose_name="库存状态",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="commerce.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU",
                "verbose_name_plural": "SKU",
                "db_table": "sku",
                "ordering": ["product", "price"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["cas"], name="product_cas_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_name_idx"),
        ),
    ]
