# Generated by Django 5.1.3 on 2026-06-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="catalog_no",
            field=models.CharField(
                blank=True, max_length=64, null=True, unique=True, verbose_name="目录号"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_l1",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="一级分类"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_l2",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="二级分类"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="concentration",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="浓度"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="formula",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="分子式"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="molecular_weight",
            field=models.FloatField(blank=True, null=True, verbose_name="分子量"),
        ),
        migrations.AddField(
            model_name="product",
            name="overview",
            field=models.TextField(blank=True, default="", verbose_name="产品概述"),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.TextField(blank=True, default="", verbose_name="SEO描述"),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(
                blank=True, default="", max_length=256, verbose_name="SEO标题"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="structure_svg",
            field=models.TextField(blank=True, default="", verbose_name="结构式SVG"),
        ),
        migrations.AddField(
            model_name="sku",
            name="concentration",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="浓度"
            ),
        ),
        migrations.AddField(
            model_name="sku",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="默认SKU"),
        ),
        migrations.AddField(
            model_name="sku",
            name="lead_time",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="交货时间"
            ),
        ),
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("datasheet", "Datasheet"),
                            ("msds", "MSDS"),
                            ("coa", "COA"),
                            ("application_note", "Application Note"),
                        ],
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=16, verbose_name="语言"),
                ),
                (
                    "version",
                    models.CharField(default="1.0", max_length=16, verbose_name="版本"),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, default="", upload_to="documents/%Y/%m/"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="原始文件名",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="commerce.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品文档",
                "verbose_name_plural": "产品文档",
                "db_table": "product_document",
                "ordering": ["-created_at"],
            },
        ),
    ]
