# Generated by Django 6.0.6 on 2026-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_product_display_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cas",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CAS 注册号，例如：73449-06-6",
                max_length=100,
                verbose_name="CAS号",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="catalog_no",
            field=models.CharField(
                blank=True,
                help_text="唯一产品编号，例如：SC8047",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="目录号",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_l1",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "nucleotides_nucleosides",
                        "Nucleotides & Nucleosides / 核苷酸/核苷",
                    ),
                    ("click_chemistry", "Click Chemistry / 点击化学"),
                    ("molecular_biology", "Molecular Biology / 分子生物学"),
                    ("proteins", "Proteins / 蛋白质"),
                    ("probes_epigenetics", "Probes & Epigenetics / 探针与表观遗传学"),
                    ("rna_technologies", "RNA Technologies / RNA 技术"),
                    ("antibodies_antigens", "Antibodies & Antigens / 抗体与抗原"),
                    (
                        "crystallography_cryoem",
                        "Crystallography & Cryo-EM / 晶体学与冷冻电镜",
                    ),
                    ("custom_synthesis", "Custom Synthesis / 定制合成"),
                ],
                default="",
                help_text="选择产品大类",
                max_length=128,
                verbose_name="一级分类 (L1)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category_l2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="选择产品子类（根据 L1 动态变化）",
                max_length=128,
                verbose_name="二级分类 (L2)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="concentration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("100 mM", "100 mM"),
                    ("50 mM", "50 mM"),
                    ("10 mM", "10 mM"),
                    ("1 mM", "1 mM"),
                    ("100 µM", "100 µM"),
                    ("10 µM", "10 µM"),
                    ("solid", "固体 (solid)"),
                    ("", "自定义输入"),
                ],
                default="",
                help_text="选择常见浓度或留空自定义",
                max_length=64,
                verbose_name="浓度",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="display_priority",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="数字越大越靠前，0 为默认排序",
                verbose_name="展示优先级",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="formula",
            field=models.CharField(
                blank=True,
                default="",
                help_text="分子式，例如：C10H15N8O12P3",
                max_length=256,
                verbose_name="分子式",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="handling_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="安全操作提示",
                verbose_name="操作注意事项",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="inchi",
            field=models.TextField(
                blank=True,
                default="",
                help_text="国际化合物标识，标准 InChI 字符串",
                verbose_name="InChI",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="lead_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("In stock, ships same day", "有货, 当天发货"),
                    ("1-3 business days", "1-3 个工作日"),
                    ("3-5 business days", "3-5 个工作日"),
                    ("1-2 weeks", "1-2 周"),
                    ("2-4 weeks", "2-4 周"),
                    ("4-6 weeks", "4-6 周"),
                    ("", "自定义输入"),
                ],
                default="",
                help_text="选择发货周期",
                max_length=100,
                verbose_name="货期",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="molecular_weight",
            field=models.FloatField(
                blank=True,
                help_text="分子量（g/mol），例如：532.2",
                null=True,
                verbose_name="分子量",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="产品全名，例如：2'-Azido-dATP Sodium Salt",
                max_length=255,
                verbose_name="产品名称",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="overview",
            field=models.TextField(
                blank=True,
                default="",
                help_text="产品详细介绍，支持 Markdown",
                verbose_name="产品概述",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="purity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("≥ 99% (HPLC)", "≥ 99% (HPLC)"),
                    ("≥ 98% (HPLC)", "≥ 98% (HPLC)"),
                    ("≥ 97% (HPLC)", "≥ 97% (HPLC)"),
                    ("≥ 95% (HPLC)", "≥ 95% (HPLC)"),
                    ("≥ 90% (HPLC)", "≥ 90% (HPLC)"),
                    ("≥ 99% (PAGE)", "≥ 99% (PAGE)"),
                    ("≥ 95% (PAGE)", "≥ 95% (PAGE)"),
                    ("≥ 98% (TLC)", "≥ 98% (TLC)"),
                    ("", "自定义输入"),
                ],
                default="",
                help_text="选择常见纯度或留空自定义",
                max_length=100,
                verbose_name="纯度",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="research_use_only",
            field=models.BooleanField(
                default=True,
                help_text="勾选表示此产品仅用于科学研究",
                verbose_name="仅限研究用途",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="搜索引擎描述，建议 120-160 字符",
                verbose_name="SEO描述",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seo_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="搜索引擎标题，建议 50-60 字符",
                max_length=256,
                verbose_name="SEO标题",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shelf_life",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P1Y", "1 年"),
                    ("P2Y", "2 年"),
                    ("P3Y", "3 年"),
                    ("P5Y", "5 年"),
                    ("", "自定义输入"),
                ],
                default="",
                help_text="选择保质期",
                max_length=20,
                verbose_name="保质期",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Dry Ice", "干冰"),
                    ("Blue Ice", "蓝冰"),
                    ("Ambient", "常温"),
                    ("Cold Pack", "冷 packs"),
                    ("", "自定义输入"),
                ],
                default="",
                help_text="选择运输方式",
                max_length=100,
                verbose_name="运输条件",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="URL 标识符，自动生成",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="smiles",
            field=models.TextField(
                blank=True,
                default="",
                help_text="简化分子输入行系统，例如：C1=NC(=C2C(=N1)N(C=N2)[C@H]3...",
                verbose_name="SMILES",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="storage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-20°C", "-20°C"),
                    ("-20°C, protect from light", "-20°C, 避光"),
                    ("-80°C", "-80°C"),
                    ("4°C", "4°C"),
                    ("4°C, protect from light", "4°C, 避光"),
                    ("Room temperature", "室温"),
                    ("Room temperature, dry", "室温, 干燥"),
                    ("", "自定义输入"),
                ],
                default="",
                help_text="选择储存温度",
                max_length=200,
                verbose_name="储存条件",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="structure_svg",
            field=models.TextField(
                blank=True,
                default="",
                help_text="分子结构 SVG 代码",
                verbose_name="结构式SVG",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="synonyms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='JSON 数组格式，例如：["2\'-F-dATP", "2-Fluoro-dATP"]',
                verbose_name="同义词",
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD ($)"), ("CNY", "CNY (¥)"), ("EUR", "EUR (€)")],
                default="USD",
                max_length=10,
                verbose_name="币种",
            ),
        ),
    ]
