# Generated by Django 5.1.3 on 2026-06-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_alter_product_cas_alter_product_catalog_no_and_more"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="current_sds",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_product",
                to="documents.sdsrevision",
                verbose_name="当前 SDS 版本",
            ),
        ),
    ]
