# Generated by Django 5.1.3 on 2026-07-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='structure_image',
            field=models.TextField(blank=True, default='', help_text='从导入的 Word 文档中提取的原始结构图（base64 data URL），原样保存，不做加工', verbose_name='文档结构图'),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure_svg',
            field=models.TextField(blank=True, default='', help_text='分子结构 SVG 代码（由 SMILES 渲染，或回退自文档结构图）', verbose_name='结构式SVG'),
        ),
    ]
