# Generated by Django 5.1.3 on 2026-07-31 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_product_structure_image_alter_product_structure_svg'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, help_text='True 表示被软删除进入回收站，默认不在列表出现，可经 restore 恢复', verbose_name='已软删(回收站)'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '软删除(归档)'), ('RESTORE', '恢复'), ('HARD_DELETE', '物理删除')], max_length=20, verbose_name='动作')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('object_repr', models.CharField(max_length=255, verbose_name='对象标识')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='快照')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='模型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_ct_obj'), models.Index(fields=['action'], name='audit_action_idx')],
            },
        ),
    ]
