# Generated by Django 5.1.3 on 2026-08-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_product_archived_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, default='', help_text='从导入的 Word 文档中提取的厂商声称用途，作为轴A 相关性的地基（docx usage × 协议领域词 F-score）', verbose_name='厂商声称用途'),
        ),
    ]
