# Generated by Django 5.1.3 on 2026-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_product_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aggregate_relevance_score',
            field=models.FloatField(blank=True, db_index=True, help_text='S5：聚合本商品所有非 weak(广播) 协议链接的三轴融合分（默认 mean）。无 evidenced 链接则为 NULL（诚实不冒充 0，排序沉底）', null=True, verbose_name='商品级相关性聚合分'),
        ),
    ]
