# Generated by Django 5.1.3 on 2026-07-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pubchem", "PubChem"),
                            ("chembl", "ChEMBL"),
                            ("pubmed", "PubMed"),
                            ("bioz", "Bioz"),
                        ],
                        max_length=20,
                        verbose_name="数据源",
                    ),
                ),
                (
                    "query_key",
                    models.CharField(
                        help_text="systematic_name / CAS / product_name 等主标识符",
                        max_length=255,
                        verbose_name="查询键",
                    ),
                ),
                (
                    "query_namespace",
                    models.CharField(
                        help_text="name / cas / smiles / inchi / inchikey / cid",
                        max_length=20,
                        verbose_name="标识符类型",
                    ),
                ),
                ("data_json", models.TextField(verbose_name="原始 API 响应 JSON")),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获取时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="过期时间"),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        default=False,
                        help_text="API 失败时回填的过期数据标记",
                        verbose_name="是否过期兜底数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据源缓存",
                "verbose_name_plural": "数据源缓存",
                "db_table": "datasource_cache",
                "indexes": [
                    models.Index(
                        fields=["source", "query_key"], name="dsc_source_key_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "query_key", "query_namespace"),
                        name="unique_datasource_cache_entry",
                    )
                ],
            },
        ),
    ]
