# Generated by Django 5.1.3 on 2026-07-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_datasource_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdsrevision',
            name='data_confidence',
            field=models.CharField(choices=[('high', '高 (PubChem CID 命中)'), ('medium', '中 (SMILES/InChI/名称解析)'), ('low', '低 (类别模板)'), ('very_low', '极低 (通用兜底)')], default='low', help_text='high=PubChem CID 命中 / medium=SMILES-InChI-名称解析 / low=类别模板 / very_low=通用兜底', max_length=10, verbose_name='数据可信度'),
        ),
        migrations.AddField(
            model_name='sdsrevision',
            name='data_source_detail',
            field=models.TextField(blank=True, default='', help_text='可读来源说明，如 PubChem CID 12345 / Category template: Oligonucleotides / Generic safety notes (no identifier matched)', verbose_name='数据来源说明'),
        ),
    ]
