# Generated by Django 5.1.3 on 2026-07-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_fix_coa_approved_to_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coa',
            options={'ordering': ['-created_at'], 'verbose_name': 'COA', 'verbose_name_plural': 'COA'},
        ),
    ]
